  wcgrid_clean:
    extends:
      file: docker-compose.yml
      service: wcgrid_handler
    environment:
      # these are just used locally to avoid typos
      trash: /var/host/trash_wcgrid_data
      dupes: /var/host/dupe_wcgrid_data
      clean: /var/host/cleaned_wcgrid_data
      processed_md5: /var/host/processed_md5
      completed_md5: /var/host/completed_md5
      uploads: /var/host/upload
      # this is the command passed to ./manage.py
      DJANGO_COMMAND: cleanwcgbatch $completed_md5 --wus=$uploads --sorted_md5=$processed_md5 --sorted_path=$clean --dupes_path=$dupes --trash_path=$trash

    volumes:
      - /cep/wcgrid/output_cep2:$completed_md5
      - /var/local/upload:$uploads
      - /var/local/cleaned_wcgrid_data:$clean
      - /var/local/dupe_wcgrid_data:$dupes
      - /var/local/trash_wcgrid_data:$trash